# Generated by Django 4.2.5 on 2023-09-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0002_auto_20210124_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
