# Generated by Django 5.0.2 on 2024-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_alter_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
