# Generated by Django 3.1.2 on 2020-10-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_ticketmessage_email_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='verification_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
