# Generated by Django 5.0.2 on 2024-02-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0006_verificationsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pushover_user_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ticketmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("C", "Customer"),
                    ("R", "Response"),
                    ("N", "Note"),
                    ("S", "System"),
                    ("E", "System Response"),
                ],
                max_length=1,
            ),
        ),
    ]
