# Generated by Django 5.0.14 on 2025-06-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_customer_pushover_user_key_alter_ticketmessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emails_blocked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('P', 'Phone'), ('W', 'Web'), ('E', 'Email'), ('O', 'Other'), ('I', 'Internal')], default='O', max_length=1),
        ),
    ]
