# Generated by Django 5.0.14 on 2025-06-14 23:32

import as207960_utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_customer_emails_blocked_alter_ticket_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPGPKey',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='support_pgpkey', primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('pgp_key', models.TextField()),
                ('primary', models.BooleanField(blank=True, default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgp_keys', to='support.customer')),
            ],
        ),
    ]
