# Generated by Django 5.0.14 on 2025-06-15 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_customerpgpkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='pgp_signature_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='pgp_signed_message',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='pgp_signing_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.customerpgpkey'),
        ),
    ]
