kind: ConfigMap
apiVersion: v1
metadata:
  name: support-django-test-conf
data:
  HOST: "support.test.as207960.net,support-test-nginx"
  DJANGO_SETTINGS_MODULE: as207960_support.settings
  EXTERNAL_URL: "https://support.test.as207960.net"
  SENTRY_ENVIRONMENT: "test"
  KEYCLOAK_SERVER_URL: "https://sso.as207960.net"
  KEYCLOAK_REALM: test
  KEYCLOAK_SCOPES: "openid email profile offline_access"
  KEYCLOAK_CLIENT_ID: "support"
  DB_HOST: "cockroachdb"
  DB_NAME: "support-test"
  FEEDBACK_URL: "none"
  EMAIL_HOST: "mx.postal.as207960.net"
  EMAIL_HOST_USER: "apikey"
  EMAIL_PORT: "25"
  EMAIL_FROM: "=?UTF-8?q?Glauca=20=2f=20AS207960=20Support=20=5bTEST=5d?= <hello-test@glauca.digital>"
  POSTAL_PUBLIC_KEY: >-
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQChELn1Fkauo6bduyGeXNca/z27OYNMd85JZMlNiycfFHaAXzgPd53OKVSbyzBuILFPYmzkfaF
    uOCW2qgvFd8cAye6qLsUAqEetiuRTPpAysX3hss1TqIML51kb0ADTmylKi3Hr553qrDy9AEMFmvaKnTH8o0YFozGk0QtlmiLtXQIDAQAB
  S3_ENDPOINT: "https://s3.as207960.net"
  S3_REGION: "garage"
  S3_BUCKET: "support-test-django"
  S3_ACCESS_KEY_ID: "GKd9decd8827525878b1ab14e2"
  S3_CUSTOM_DOMAIN: "support-test-django.content.as207960.net"
  STATIC_URL: "https://support-test-django.content.as207960.net/"
  MEDIA_URL: "https://support-test-django.content.as207960.net/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-django-test
  labels:
    app: support-test
    part: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-test
      part: django
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: support-test
        part: django
    spec:
      initContainers:
        - name: django
          image: as207960/support-django:(version)
          imagePullPolicy: Always
          command: ["sh", "-c", "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py sync-keycloak"]
          envFrom:
            - configMapRef:
                name: support-django-test-conf
            - secretRef:
                name: support-db-test-creds
              prefix: "DB_"
            - secretRef:
                name: support-django-test-secret
            - secretRef:
                name: support-test-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: support-test-email
              prefix: "EMAIL_"
            - secretRef:
                name: support-test-celery
              prefix: "CELERY_"
            - secretRef:
                name: support-recaptcha
              prefix: "RECAPTCHA_"
            - secretRef:
                name: support-test-s3
      containers:
        - name: gunicorn
          image: as207960/support-django:(version)
          imagePullPolicy: Always
          command: ["gunicorn", "-w", "8", "-b", "[::]:8000", "--forwarded-allow-ips", "*", "--access-logfile", "-", "--timeout=90", "as207960_support.wsgi:application"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: support-django-test-conf
            - secretRef:
                name: support-db-test-creds
              prefix: "DB_"
            - secretRef:
                name: support-django-test-secret
            - secretRef:
                name: support-test-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: support-test-email
              prefix: "EMAIL_"
            - secretRef:
                name: support-test-celery
              prefix: "CELERY_"
            - secretRef:
                name: support-recaptcha
              prefix: "RECAPTCHA_"
            - secretRef:
                name: support-test-s3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-celery-test
  labels:
    app: support-test
    part: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-test
      part: celery
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: support-test
        part: celery
    spec:
      containers:
        - name: celery
          image: as207960/support-django:(version)
          imagePullPolicy: Always
          command: ["celery", "-A", "as207960_support", "worker", "--loglevel=INFO", "-c", "32"]
          envFrom:
            - configMapRef:
                name: support-django-test-conf
            - secretRef:
                name: support-db-test-creds
              prefix: "DB_"
            - secretRef:
                name: support-django-test-secret
            - secretRef:
                name: support-test-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: support-test-email
              prefix: "EMAIL_"
            - secretRef:
                name: support-test-celery
              prefix: "CELERY_"
            - secretRef:
                name: support-recaptcha
              prefix: "RECAPTCHA_"
            - secretRef:
                name: support-test-s3
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: support-test-django
spec:
  podSelector:
    matchLabels:
      app: support-test
      part: django
  policyTypes:
  - Ingress
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
        podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: support-test-celery
spec:
  podSelector:
    matchLabels:
      app: support-test
      part: celery
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: Service
metadata:
  name: support-django-test
  labels:
    app: support-test
    part: django
spec:
  selector:
    app: support-test
    part: django
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-ingress-test
  annotations:
    cert-manager.io/cluster-issuer: "gts"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - support.test.as207960.net
      secretName: support-tls
  rules:
    - host: support.test.as207960.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: support-django-test
                port:
                  number: 8000
