kind: ConfigMap
apiVersion: v1
metadata:
  name: support-django-conf
data:
  HOST: "support.as207960.net,support-nginx"
  DJANGO_SETTINGS_MODULE: "as207960_support.settings"
  EXTERNAL_URL: "https://support.as207960.net"
  SENTRY_ENVIRONMENT: "prod"
  KEYCLOAK_SERVER_URL: "https://sso.as207960.net"
  KEYCLOAK_REALM: "master"
  KEYCLOAK_SCOPES: "openid email profile offline_access"
  KEYCLOAK_CLIENT_ID: "support"
  DB_HOST: "cockroachdb"
  DB_NAME: "support"
  FEEDBACK_URL: "http://feedback-nginx"
  EMAIL_HOST: "mx.postal.as207960.net"
  EMAIL_HOST_USER: "apikey"
  EMAIL_PORT: "25"
  EMAIL_FROM: "=?UTF-8?q?Glauca=20=2f=20AS207960=20Support?= <hello@glauca.digital>"
  POSTAL_PUBLIC_KEY: >-
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQChELn1Fkauo6bduyGeXNca/z27OYNMd85JZMlNiycfFHaAXzgPd53OKVSbyzBuILFPYmzkfaF
    uOCW2qgvFd8cAye6qLsUAqEetiuRTPpAysX3hss1TqIML51kb0ADTmylKi3Hr553qrDy9AEMFmvaKnTH8o0YFozGk0QtlmiLtXQIDAQAB
  S3_ENDPOINT: "https://s3.as207960.net"
  S3_REGION: "garage"
  S3_BUCKET: "support-django"
  S3_ACCESS_KEY_ID: "GKafeb0c763f2d42517e0f071a"
  S3_CUSTOM_DOMAIN: "support-django.content.as207960.net"
  STATIC_URL: "https://support-django.content.as207960.net/"
  MEDIA_URL: "https://support-django.content.as207960.net/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-django
  labels:
    app: support
    part: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support
      part: django
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: support
        part: django
    spec:
      initContainers:
        - name: django
          image: as207960/support-django:(version)
          imagePullPolicy: Always
          command: ["sh", "-c", "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py sync-keycloak"]
          envFrom: &envFrom
            - configMapRef:
                name: support-django-conf
            - secretRef:
                name: support-db-creds
              prefix: "DB_"
            - secretRef:
                name: support-django-secret
            - secretRef:
                name: support-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: support-email
              prefix: "EMAIL_"
            - secretRef:
                name: support-celery
              prefix: "CELERY_"
            - secretRef:
                name: support-recaptcha
              prefix: "RECAPTCHA_"
            - secretRef:
                name: support-s3
            - secretRef:
                name: support-stripe
              prefix: "STRIPE_"
            - secretRef:
                name: support-pushover
              prefix: "PUSHOVER_"
      containers:
        - name: gunicorn
          image: as207960/support-django:(version)
          imagePullPolicy: Always
          command: ["gunicorn", "-w", "8", "-b", "[::]:8000", "--forwarded-allow-ips", "*", "--access-logfile", "-", "--timeout=90", "as207960_support.wsgi:application"]
          ports:
            - containerPort: 8000
          envFrom: *envFrom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-celery
  labels:
    app: support
    part: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support
      part: celery
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: support
        part: celery
    spec:
      containers:
        - name: celery
          image: as207960/support-django:(version)
          imagePullPolicy: Always
          command: ["celery", "-A", "as207960_support", "worker", "--loglevel=INFO", "-c", "32"]
          envFrom:
            - configMapRef:
                name: support-django-conf
            - secretRef:
                name: support-db-creds
              prefix: "DB_"
            - secretRef:
                name: support-django-secret
            - secretRef:
                name: support-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: support-email
              prefix: "EMAIL_"
            - secretRef:
                name: support-celery
              prefix: "CELERY_"
            - secretRef:
                name: support-recaptcha
              prefix: "RECAPTCHA_"
            - secretRef:
                name: support-s3
            - secretRef:
                name: support-stripe
              prefix: "STRIPE_"
            - secretRef:
                name: support-pushover
              prefix: "PUSHOVER_"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-keycloak-events
  labels:
    app: support
    part: keycloak-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support
      part: keycloak-events
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: support
        part: keycloak-events
    spec:
      containers:
        - name: keycloak-events
          image: as207960/support-django:(version)
          imagePullPolicy: Always
          command: ["sh", "-c", "python3 manage.py keycloak-events"]
          envFrom:
            - configMapRef:
                name: support-django-conf
            - secretRef:
                name: support-db-creds
              prefix: "DB_"
            - secretRef:
                name: support-django-secret
            - secretRef:
                name: support-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: support-email
              prefix: "EMAIL_"
            - secretRef:
                name: support-celery
              prefix: "CELERY_"
            - secretRef:
                name: support-recaptcha
              prefix: "RECAPTCHA_"
            - secretRef:
                name: support-s3
            - secretRef:
                name: support-stripe
              prefix: "STRIPE_"
            - secretRef:
                name: support-pushover
              prefix: "PUSHOVER_"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: support-django
spec:
  podSelector:
    matchLabels:
      app: support
      part: django
  policyTypes:
  - Ingress
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
        podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: support-celery
spec:
  podSelector:
    matchLabels:
      app: support
      part: celery
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: support-keycloak-events
spec:
  podSelector:
    matchLabels:
      app: support
      part: keycloak-events
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: Service
metadata:
  name: support-django
  labels:
    app: support
    part: django
spec:
  selector:
    app: support
    part: django
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-ingress
  annotations:
    cert-manager.io/cluster-issuer: "gts"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - support.as207960.net
      secretName: support-tls
  rules:
    - host: support.as207960.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: support-django
                port:
                  number: 8000
